export default [
  { projectId: 1, title: '안녕하세요?', confirmed: 2, recruitment: 4 },
  { projectId: 2, title: 'ㅋㅋㅋㅋㅋㅋ', confirmed: 3, recruitment: 4 },
  { projectId: 3, title: '[KR] kim chi fighter', confirmed: 1, recruitment: 4 },
  { projectId: 4, title: 'Lets greep!', confirmed: 1, recruitment: 4 },
  { projectId: 5, title: 'oma ewa mo sindae iru', confirmed: 1, recruitment: 4 },
  { projectId: 6, title: 'nani?', confirmed: 1, recruitment: 4 },
  { projectId: 7, title: 'im iron man', confirmed: 3, recruitment: 4 },
  { projectId: 8, title: 'nice project!', confirmed: 3, recruitment: 4 },
  { projectId: 9, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { projectId: 10, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { projectId: 11, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { projectId: 12, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { projectId: 13, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { projectId: 14, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { projectId: 15, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
]
