export default [
  { postId: 1, title: '안녕하세요?', confirmed: 2, recruitment: 4 },
  { postId: 2, title: 'ㅋㅋㅋㅋㅋㅋ', confirmed: 3, recruitment: 4 },
  { postId: 3, title: '[KR] kim chi fighter', confirmed: 1, recruitment: 4 },
  { postId: 4, title: 'Lets greep!', confirmed: 1, recruitment: 4 },
  { postId: 5, title: 'oma ewa mo sindae iru', confirmed: 1, recruitment: 4 },
  { postId: 6, title: 'nani?', confirmed: 1, recruitment: 4 },
  { postId: 7, title: 'im iron man', confirmed: 3, recruitment: 4 },
  { postId: 8, title: 'nice project!', confirmed: 3, recruitment: 4 },
  { postId: 9, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { postId: 10, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { postId: 11, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { postId: 12, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { postId: 13, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { postId: 14, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
  { postId: 15, title: 'just DO IT!', confirmed: 1, recruitment: 4 },
]
